version: '3.3'

services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - 8080:80
