version: '3.3'

services:
  database:
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306

  wordpress:
    image: wordpress:php7.3-fpm
    restart: always
    volumes:
      - ./wordpress:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    links:
      - database
    env_file:
      - .env
    ports:
      - 9000

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/wordpress.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./wordpress:/var/www/html
    ports:
      - 80
    links:
      - wordpress

volumes:
  db_data:
